INSERT INTO roles(name) VALUES('ROLE_CHEF');
INSERT INTO roles(name) VALUES('ROLE_PCR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_AGENT_INCENDIE');
INSERT INTO roles(name) VALUES('ROLE_CHEF_INCENDIE');